Minigames:
 Amount: 5
 1: "SLENDERMAN"
  item: "STICK"
 2: "FUCK"
 3: "420"
 4: "69"
 5: "GAYFAG"

#ip of server and a port that isn't in use. This will have to be added to the other servers config
Port: 1000

#add every server except this one with the port you specified in the other config
Servers:
    - "ip:port"